export const images = {
  hero: '/images/concept-hero.jpg', city: '/images/concept-city.jpg', fashion: '/images/concept-fashion.jpg',
  music: '/images/concept-music.jpg', dance: '/images/concept-dance.jpg', metro: '/images/concept-metro.jpg',
};

export const imageAlts = {
  [images.hero]: 'A figure facing a luminous skyline at night',
  [images.city]: 'A portrait layered with the lights and windows of a city',
  [images.fashion]: 'Cinematic portraits surrounded by blurred night-time colour',
  [images.music]: 'Figures framed by a red-lit window in a blue building',
  [images.dance]: 'A small figure beneath an oversized red projection',
  [images.metro]: 'An atmospheric view of a city in the late hours',
};

const entries = [
  {
    title: 'The City After 2AM', slug: 'the-city-after-2am', category: 'Culture', type: 'Essay', date: '08.09.26', author: 'Mira Vale', image: images.city, layout: 'essay',
    blurb: 'An observation of what happens when everybody else goes home.',
    intro: 'The city changes character somewhere between the last train and the first bus. Streets built to move thousands become private rooms. A traffic light performs for nobody. The night is another city, using the same address.',
    quote: 'The city belongs to different people after midnight.',
    sections: [
      ['The last train', 'Imagine a station just after the final departure. The platform is still warm with the movement of people, but its purpose has gone. A paper cup rolls towards a drain. An announcement repeats a promise the timetable can no longer keep. The station has become a room, and for a moment you notice how large that room is.', 'Outside, the streets retain the instructions of the day: stop, turn, buy, wait. With fewer people to obey them, those instructions look strangely theatrical. A crossing changes from red to green for an audience of one. An illuminated advertisement tells an empty pavement that a better life is available upstairs. The expensive surfaces stay lit; the inexpensive places quietly get to work.', 'This is an imagined walk, not a report from a particular street. Its details belong to a familiar interval in many cities: the hours when leisure and labour pass each other without quite making eye contact. One person is looking for something to eat. Another has already begun making tomorrow’s bread. Their clocks share a number, but not a meaning.'],
      ['A different public', 'It is tempting to call the city empty. Usually that means it has emptied of the people we expect to see. Someone is cleaning a lobby. Someone is waiting for a fare. Someone is carrying a bag of uniforms to a bus stop whose next arrival is still an hour away. Quiet is not the same thing as absence.', 'Night makes the work of maintaining a city briefly visible. A delivery van parks where an executive car stood at noon. Bins cross a marble entrance. The backstage door opens onto the same pavement as the front door. If you stay still long enough, the grand building becomes a collection of ordinary tasks.', 'There is freedom here, but it is not equally distributed. The long walk that feels cinematic to one person can be an exhausting necessity to another. Darkness offers anonymity and asks for caution. An honest account of the night has to hold both ideas at once, without turning either into a slogan.'],
      ['Before the first bus', 'A photograph can make almost any late-night corner look like a discovery. Reflections double the street; a red sign supplies a ready-made mood. The harder thing is to look without immediately converting what you see into an image. To let the corner remain a corner, occupied by people with somewhere else to be.', 'Try listening instead. A refrigerator behind a closed shop. A bicycle chain. The brief electric whine of a bus slowing at a junction. Daylight bundles these sounds into background noise. At night they arrive separately, each attached to a small action. The city seems less like a single machine and more like many lives negotiating the same space.', 'Then the sky pales. The first commuters introduce a new kind of walking: direct, practised, already elsewhere in the mind. Shutters rise. The bakery becomes a shop again. Nobody announces the handover. The city has not slept, and it has not been waiting for us. It has simply changed hands.'],
    ], gallery: [images.city, images.metro, images.hero],
  },
  {
    title: 'Clothes Made for Disappearing', slug: 'clothes-made-for-disappearing', category: 'Fashion', type: 'Editorial', date: '06.09.26', author: 'Lea Arden', image: images.fashion, layout: 'fashion',
    blurb: 'Night dressing as camouflage, refusal and private ritual.',
    intro: 'Some clothes announce an arrival. Others make room for an exit. This is a wardrobe for the second kind of entrance: soft edges, useful pockets, and a silhouette that does not owe the room an explanation.',
    quote: 'Getting dressed can be a way of keeping something to yourself.',
    sections: [
      ['01 / The coat', 'Begin with a coat that is slightly too large. Not exaggerated enough to become an event, just generous enough to put a small distance between the body and the world. The shoulder falls away from its expected position. The sleeve hides the heel of the hand. Under a street lamp, the cloth becomes a single dark shape.', 'In this fictional editorial, the clothes have no labels. That is deliberate. We are interested in what a garment permits, not what it certifies. The coat lets its wearer stand outside a crowded doorway without becoming part of the queue. It can hold a book, a folded scarf, the evidence of another part of the day.', 'Black is not a single colour after sunset. It separates into blue, brown, grey and the green of a nearby sign. A photograph tends to flatten those differences; movement restores them. A good dark outfit is full of small disagreements that become visible only when the wearer turns.'],
      ['02 / The borrowed shirt', 'The shirt could belong to someone else. Its collar has softened. One cuff is rolled higher than the other, because symmetry was not the point. Against the severity of the coat it introduces an ordinary intimacy: something washed, worn and chosen again.', 'Fashion often describes a look through the attention it might attract. Here, attention is a resource the wearer gets to manage. A bright lining appears only when a hand reaches into a pocket. A silver fastening catches light for a fraction of a second. The detail exists without demanding a witness.', 'Disappearing does not mean becoming invisible. It means refusing to make every choice legible at a glance. Clothes can be a boundary as much as a message. A person can enjoy the sensation of a beautiful fabric without volunteering the story of where it came from or what it is supposed to say.'],
      ['03 / Shoes for the way home', 'The final decision is practical. Choose shoes for the distance home, not just the room you intend to enter. The romantic image of a night out usually stops before the pavement becomes uncomfortable. A useful wardrobe continues beyond the photograph.', 'There is a particular confidence in leaving a little room for weather, fatigue and a change of plan. A sole with grip. A fastening that works with cold fingers. Fabric that can sit on a station bench without requiring an apology. These are design decisions, and they deserve the same attention as a dramatic silhouette.', 'By morning, the outfit will be separated into objects again: coat on a chair, shirt over a door, shoes beside the bed. The temporary character they made together has gone. What remains is less spectacular and more valuable—a collection of things that helped someone move through the world on their own terms.'],
    ], gallery: [images.fashion, images.city, images.dance],
  },
  {
    title: 'Bedroom Producers Are Building the New Underground', slug: 'bedroom-producers', category: 'Music', type: 'Essay', date: '04.09.26', author: 'Jules Park', image: images.music, layout: 'music',
    blurb: 'A scene can begin with one unfinished track and someone willing to listen.',
    intro: 'Before there is a stage, there is a room. A laptop balances beside a glass of water. Headphones leak a thin hi-hat into the quiet. The track has seven names, all of them variations on “final”.',
    quote: 'A scene begins when somebody listens closely enough to answer.',
    sections: [
      ['Rooms before venues', 'Picture a producer working after the building has gone quiet. The bass is mostly imagined because the neighbours are asleep. A melody has been moved up an octave, then down again. The room is a studio because someone is using it as one, not because the equipment has passed a test.', 'This is a fictional composite, not an interview or a claim about a particular music scene. It begins with a question: what makes a private practice become a shared culture? Having access to recording tools is one part of the answer. Finding people who make those tools feel worth returning to is another.', 'The first audience might be a group chat with four members. A file arrives without artwork or a release date. Someone replies with a timestamp: the sound at 1:42, keep that. Someone else sends back a drum pattern. The exchange is small, but it contains the essential structure of a scene—attention, response, and the invitation to try again.'],
      ['The unfinished version', 'An unfinished track asks for a different kind of listening. It has not yet learned how to defend itself. Its awkward transition may be a problem or the most interesting thing about it. A friend can hear possibility where a public comment section would hear a mistake.', 'There is no need to romanticise the room. Isolation can be dull. A chair can hurt your back. Software can turn an evening into a long negotiation with a missing file. The mythology of the solitary genius leaves out the ordinary support that makes solitude bearable: borrowed equipment, patient housemates, a friend who remembers to ask how it is going.', 'The underground is sometimes imagined as a hidden place with a door. Here it is closer to a habit of exchange. People pass sounds between rooms, disagree about a mix, share a space for an evening. What connects them is not secrecy, but the ability to make something without first proving that a large audience will want it.'],
      ['Let the room get bigger', 'Eventually a track leaves the headphones. Played through unfamiliar speakers, it changes shape. A bass note overwhelms the room. A tiny texture disappears. Someone moves to a rhythm its maker no longer notices. The work becomes public by becoming partly unpredictable.', 'A venue matters because it lets a group hear itself together. But the room that preceded it should not be treated as an embarrassing early chapter. Its limits may have created the music’s most distinctive decisions: a quiet vocal, a rough edit, a drum sound assembled from whatever was already there.', 'Perhaps building a new underground means preserving some of that permission as the audience grows. Leave space for the strange version. Listen before asking for a link. Remember the person who heard the first draft and answered with something more useful than a number. The next scene may already be playing softly through the wall.'],
    ], gallery: [images.music, images.metro, images.dance],
  },
  {
    title: 'The Death of the Dance Floor', slug: 'death-of-the-dance-floor', category: 'Culture', type: 'Essay', date: '02.09.26', author: 'Mira Vale', image: images.dance,
    blurb: 'What changes when a night out becomes a document of itself?',
    intro: 'A room full of people can still feel like an audience. Somewhere between the raised phone and the next song, dancing becomes something we watch ourselves doing.',
    quote: 'The best part of the night might be the part nobody kept.',
    sections: [['A room, not a feed', 'Imagine a dance floor photographed every thirty seconds. Nothing terrible happens. The music continues. But the possibility of being recorded changes the way some bodies occupy the room. A spontaneous movement acquires an imaginary second audience.', 'There is nothing inherently empty about taking a photograph. A picture can be a souvenir, an invitation, a way to remember a friend. The question is whether the record serves the experience or starts giving it instructions.'], ['Permission to forget', 'A good dance floor makes a temporary agreement possible: we are here together, and this does not need to become anything else. The agreement is fragile. It relies on the room, the people running it, and the care people take with one another.', 'The title of this essay is a provocation, not an obituary. Dance floors are not dead. But the freedom to be briefly unrecorded is worth making space for. Let one song end without checking how it looked.']], gallery: [images.dance, images.music],
  },
  {
    title: 'Why Does Everything Look Better at Night?', slug: 'better-at-night', category: 'Art', type: 'Essay', date: '30.08.26', author: 'Lea Arden', image: images.hero,
    blurb: 'On shadow, suggestion and the freedom of not seeing everything.',
    intro: 'Darkness is an editor. It removes the sign you disliked, the unfinished facade, the awkward gap between two buildings. What remains feels strangely intentional.',
    quote: 'A shadow leaves room for the viewer to finish the image.',
    sections: [['What the light leaves out', 'Daylight gives us information in excess. At night, a single window can organise an entire street. The eye builds a composition around what is visible and quietly invents the rest. Beauty may begin in that act of participation.', 'This is not a rule of photography so much as an invitation to look. Find a familiar corner after sunset. Notice which details become important and which ones cease to matter. The corner has not changed, but its hierarchy has.'], ['An incomplete picture', 'The danger is confusing a compelling image with a complete account. A glowing window tells us little about the life behind it. A dramatic shadow can hide an ordinary inconvenience.', 'Perhaps the useful lesson is not that everything looks better at night. It is that seeing less can help us notice differently. Bring some of that patience back into the day.']], gallery: [images.hero, images.city],
  },
  {
    title: '24 Hours Without Daylight', slug: 'without-daylight', category: 'Art', type: 'Visual notebook', date: '27.08.26', author: 'Orin North', image: images.metro, layout: 'photo',
    blurb: 'An imagined day told through interiors, reflections and borrowed light.',
    intro: 'This is a visual exercise, not a documentary record: assemble a day from images in which the sun never appears. Let the sequence provide the clock.',
    quote: 'Time can be measured in changes of light, even when there is no sunrise.',
    sections: [['18:00 / Enter', 'A station is a useful beginning because it offers a way out. Its light belongs to no particular hour. Arrive at six in the evening or six in the morning and the same surfaces will return the same pale reflection.', 'The images in this notebook are presented as a fictional sequence. The times describe a rhythm for reading them, not the circumstances in which they were made.'], ['02:00 / Between', 'A window divides a room from a city. Each side borrows light from the other. In the glass they become a third place that exists only from this angle.', 'Look at the sequence slowly. The gallery opens into a space with fewer distractions; use the arrows to move between frames. A photograph does not need to be understood immediately to hold your attention.'], ['18:00 / Return', 'At the end, return to the first image. Repetition makes a small difference visible: not in the photograph, but in what you bring to it. The invented day closes where it began.']], gallery: [images.metro, images.hero, images.city, images.music],
  },
  {
    title: 'No Signal', slug: 'no-signal', category: 'Music', type: 'Notebook', date: '25.08.26', author: 'Jules Park', image: images.metro,
    blurb: 'A listening exercise for a room with no notifications.',
    intro: 'Put one record on. Place the phone in another room. This is a small experiment in hearing what happens between the parts you already know.',
    quote: 'Attention has a sound: the detail you missed the first time.',
    sections: [['Side A', 'The opening minute feels longer without anything else to do. A familiar track reveals an unfamiliar texture: a breath before a phrase, the soft edge of a cymbal, a note that seems to arrive from another room.', 'You do not have to turn listening into a test of taste. Choose something you already love. The point is to change the conditions of attention, not to collect a more impressive opinion.'], ['Side B', 'When the music stops, resist immediately replacing it. Listen to what the room contributes. Traffic, a pipe, someone moving upstairs. Silence is rarely empty; it is simply less arranged.', 'Then put the record on again, or leave it there. Nothing has to be posted, rated or completed. For once, the experience can be exactly the size of the time it took.']], gallery: [images.metro, images.music],
  },
  {
    title: 'When Everyone Goes Home', slug: 'everyone-goes-home', category: 'Fashion', type: 'Notebook', date: '21.08.26', author: 'Lea Arden', image: images.fashion,
    blurb: 'The quiet afterlife of an outfit, once its audience has gone.',
    intro: 'A jacket hangs over a chair with the shape of the evening still in it. On the floor, a pair of shoes points in slightly different directions.',
    quote: 'An outfit ends slowly, one object at a time.',
    sections: [['The chair', 'There is a kind of accidental styling that happens only after an event. A scarf falls against a sleeve. The lining of a coat becomes its most visible surface. Freed from the body, clothes form a temporary portrait of the person who has just left them there.', 'The chair is not a display. Its arrangement follows fatigue, habit and the intention to deal with everything tomorrow. That is what makes it interesting.'], ['Morning light', 'In daylight, the dramatic shirt is ordinary fabric again. A small mark records a drink, a meal, or a moment of carelessness. It is evidence of use rather than a flaw in the image.', 'Wear something because it lets you live the evening you want. Let it come home looking as though something happened.']], gallery: [images.fashion, images.city],
  },
];

export const stories = entries.map((story, index) => ({
  ...story, id: String(index + 1).padStart(3, '0'), issue: '01',
  read: `${String(Math.max(2, Math.ceil([story.intro, ...story.sections.flat()].join(' ').split(/\s+/).length / 200))).padStart(2, '0')} min`,
}));
